flags:
  client:
    paths:
      - client/
    carryforward: false
  server:
    paths:
      - server/
    carryforward: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
