//import libraries
import express from 'express';
import morgan from 'morgan';
import cors from "cors";

//include models in order to define associations
import User from './models/user.js';
import Category from './models/category.js';
import Feed from './models/feed.js';
import Article from './models/article.js';

//routes
import categoryRoutes from "./routes/category.js";
import feedRoutes from "./routes/feed.js";
import articleRoutes from "./routes/article.js";
import crawlRoutes from "./routes/crawl.js";
import managerRoutes from "./routes/manager.js";
import settingRoutes from "./routes/setting.js";
import feverRoutes from "./routes/fever.js";
import healthRoutes from "./routes/health.js";
import cleanupRoutes from "./routes/cleanup.js";
import authRoutes from "./routes/auth.js";
import userRoutes from "./routes/user.js";
import mcpRoutes from "./routes/mcp.js";
import agentRoutes from "./routes/agent.js";

//controller
import errorController from "./controllers/error.js";

//init cache
import cache from "./util/cache.js";

//create express app
const app = express();

//use morgan for logging
app.use(morgan('[:date[clf]] :remote-addr - :method :url -> :status (:response-time ms)'));

//serve the content straight from the distribution folder (output after npm run build)
app.use(express.static("dist"));

//use cors
app.use(cors());

//parse incoming requests
//body-parser is deprecated in express 4.16.0 and later, so we can use express's built-in middleware instead
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

//set headers for CORS
app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "OPTIONS, GET, POST, PUT, PATCH, DELETE"
  );
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  next();
});

//serve out the APIs
app.use("/api/categories", categoryRoutes);
app.use("/api/feeds", feedRoutes);
app.use("/api/articles", articleRoutes);
app.use("/api/crawl", crawlRoutes);
app.use("/api/manager", managerRoutes);
app.use("/api/setting", settingRoutes);
app.use("/api/fever", feverRoutes);
app.use("/api/health", healthRoutes);
app.use("/api/cleanup", cleanupRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/mcp", mcpRoutes);
app.use("/agent", agentRoutes);
app.use(errorController.get404);

//define relationships
User.hasMany(Category, { constraints: true, onDelete: 'CASCADE' });
Feed.belongsTo(Category, { constraints: true, onDelete: 'CASCADE' });
Category.hasMany(Feed);
Article.belongsTo(Feed, { constraints: true, onDelete: 'CASCADE' });
Feed.hasMany(Article);

//start the server
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server has started on port ${port}!`);
});

process.on('uncaughtException', err => {
  if (err.name === 'RequestError') {
    //these errors are generated by a third-party package called got: https://github.com/sindresorhus/got#gotrequesterror
    //we will just log to console only to avoid whole application crashes
    console.error('UncaughtException:', err.message);
  } else {
    console.error('UncaughtException:', err);
  }
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled Rejection at:', promise, 'reason:', reason);
});

//initialize cache for hotlinks
cache.init();

//update cache every five minutes
const CACHE_REFRESH_INTERVAL = 5 * 60 * 1000; // 5 minutes in milliseconds
setInterval(() => {
  cache.init();
}, CACHE_REFRESH_INTERVAL);