title: RSSMonster
description: Signal-driven RSS reader that prioritizes what matters
theme: just-the-docs
url: https://pietheinstrengholt.github.io/rssmonster

aux_links:
  RSSMonster on GitHub: https://github.com/pietheinstrengholt/rssmonster
