title: RSSMonster
description: Signal-driven RSS reader that prioritizes what matters
theme: just-the-docs
url: https://pietheinstrengholt.github.io/rssmonster
logo: "/assets/rssmonster-logo.webp"
favicon_ico: "/assets/favicon.ico"

aux_links:
  RSSMonster on GitHub: https://github.com/pietheinstrengholt/rssmonster
