import OpenAI from "openai";
import dotenv from "dotenv";
dotenv.config();

/**
 * Summarizes article content using OpenAI
 * @param {string} content - The article content to summarize
 * @param {string} language - Optional language hint for the content
 * @returns {Promise<string>} - The summarized content
 */
export const summarizeContent = async (content) => {
  try {
    // Validate input
    if (!content || typeof content !== 'string' || content.trim().length === 0) {
      throw new Error('Invalid content provided for summarization');
    }

    // Check if API key is configured
    if (!process.env.OPENAI_API_KEY) {
      console.warn('OPENAI_API_KEY not configured. Skipping summarization.');
      return content;
    }

    // Initialize OpenAI client
    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY
    });

    const modelName = process.env.OPENAI_MODEL_NAME || 'gpt-4';

    // Create the summarization prompt
    const prompt = `Remove any advertisements or promotional content and return a concise summary in text format using the original language. Focus on the main points and key information. Keep the summary clear and informative.

Content:
${content}`;

    // Call OpenAI API
    const completion = await openai.chat.completions.create({
      model: modelName,
      messages: [
        {
          role: "system",
          content: "You are a helpful assistant that summarizes article content. Remove advertisements and promotional content, and provide clear, concise summaries in the same language as the original content."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.3,
      max_completion_tokens: 500
    });

    // Extract and return the summary
    const summary = completion.choices[0]?.message?.content;
    
    if (!summary) {
      console.warn('No summary generated by OpenAI. Returning original content.');
      return content;
    }

    return summary.trim();

  } catch (error) {
    console.error('Error in summarizeContent:', error.message);
    // Return original content if summarization fails
    return content;
  }
};

export default {
  summarizeContent
};
