name: Azure Web App

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'client/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install packages and build
      run: |
        npm install
        npm run build --if-present
      working-directory: server
      env:
        CI: true

    - name: Zip artifact for deployment
      run: cd server && zip -r ../release.zip .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rssmonster-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2dd7d8e7c60b483f86aabb734cd49aa0 }}
        package: .

    - name: Delete zip file
      run: rm release.zip