name: Deploy RSSMonster

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          bash /home/piethein/deploy-dev.sh